# Generated by Django 4.2 on 2023-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_customer_updation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_manager',
            name='updation_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
