# Generated by Django 4.2 on 2023-10-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_cl_manager_updation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_manager',
            name='updation_date',
        ),
    ]
